name = "cloudflare-docker-proxy"
compatibility_date = "2024-01-01"
main = "src/index.js"

# 删除顶层的 routes 配置
# [routes]
# pattern = "*.wesz.fun"
# custom_domain = true

# 删除顶层的 vars
# [vars]
# CUSTOM_DOMAIN = "wesz.fun"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.wesz.fun", custom_domain = true },
  { pattern = "quay.wesz.fun", custom_domain = true },
  { pattern = "gcr.wesz.fun", custom_domain = true },
  { pattern = "k8s-gcr.wesz.fun", custom_domain = true },
  { pattern = "k8s.wesz.fun", custom_domain = true },
  { pattern = "ghcr.wesz.fun", custom_domain = true },
  { pattern = "cloudsmith.wesz.fun", custom_domain = true }
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""
CUSTOM_DOMAIN = "wesz.fun"  # 将 CUSTOM_DOMAIN 移到这里