name = "cloudflare-docker-proxy"
compatibility_date = "2024-01-01"  # 建议更新到最新的兼容性日期

main = "src/index.js"  # 明确指定入口文件
compatibility_flags = ["nodejs_compat"]  # 如果需要 Node.js 兼容性

[vars]
CUSTOM_DOMAIN = "wesz.fun"

[routes]
pattern = "*.wesz.fun"
custom_domain = true

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.wesz.fun", custom_domain = true },
  { pattern = "quay.wesz.fun", custom_domain = true },
  { pattern = "gcr.wesz.fun", custom_domain = true },
  { pattern = "k8s-gcr.wesz.fun", custom_domain = true },
  { pattern = "k8s.wesz.fun", custom_domain = true },
  { pattern = "ghcr.wesz.fun", custom_domain = true },
  { pattern = "cloudsmith.wesz.fun", custom_domain = true }
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""